### ISSUE TITLE
Hot reload is not working on Client Side

### ISSUE THREAD

**Issue by snkhan120** [Thomas-Max99/mern-app-setup#1]
Salaam,

I really appreciate your effort, this is a very good example with latest node modules,

I figure out the problem that hot reloading is not working on react client, everytime I have to run **npm run development** for react changes

**Comment by Thomas-Max99** [comment]
Walaykum Salam,

Thanks for signaling the issues. To resolve it, call the compile method in the _server.js_ file by adding the following lines:

`**import devBundle from './devBundle.js'**
 const app = express()
**devBundle.compile(app)**`

That will initialize Webpack to compile automatically the client-side code when the server is run. These two highlighted lines  should be commented out when building the application code for production.

**Comment by snkhan120** [comment]
> Walaykum Salam,
> 
> Thanks for signaling the issues. To resolve it, call the compile method in the _server.js_ file by adding the following lines:
> 
> **`import devBundle from './devBundle.js'`** ` const app = express()` **`devBundle.compile(app)`**
> 
> That will initialize Webpack to compile automatically the client-side code and enable hot-reloading when the server is run. These two highlighted lines should be commented out when building the application code for production.

Its work! Thanks Man
